In [1]:
import pandas as pd

In [3]:
df=pd.read_csv(r"C:\Study\All Projects\Python Project\googleplaystore.csv")
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [5]:
df.tail()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [7]:
df.shape

(10841, 13)

In [30]:
(df.isnull()).sum()

App                  0
Category             0
Rating            1474
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
Genres               0
Last Updated         0
Current Ver          8
Android Ver          3
dtype: int64

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  object
 1   Category        10841 non-null  object
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  object
 4   Size            10841 non-null  object
 5   Installs        10841 non-null  object
 6   Type            10840 non-null  object
 7   Price           10841 non-null  object
 8   Content Rating  10840 non-null  object
 9   Genres          10841 non-null  object
 10  Last Updated    10841 non-null  object
 11  Current Ver     10833 non-null  object
 12  Android Ver     10838 non-null  object
dtypes: float64(1), object(12)
memory usage: 1.1+ MB

In [13]:
df.describe(include='all')

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
count,10841,10841,9367.000000,10841,10841,10841,10840,10841,10840,10841,10841,10833,10838
unique,9660,34,NaN,6002,462,22,3,93,6,120,1378,2832,33
top,ROBLOX,FAMILY,NaN,0,Varies with device,"1,000,000+",Free,0,Everyone,Tools,"August 3, 2018",Varies with device,4.1 and up
freq,9,1972,NaN,596,1695,1579,10039,10040,8714,842,326,1459,2451
mean,NaN,NaN,4.193338,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,0.537431,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,4.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,4.300000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,4.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,19.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Counts of App title with astrology

In [20]:
len(df[df['App'].str.contains('Astrology',case=False)])

3

# Find average of App Rating

In [31]:
df['Rating'].mean()

4.193338315362448

# Find the number of unique category

In [36]:
df['Category'].nunique()

34

# Which category is getting highest average rating

In [41]:
df.groupby('Category')['Rating'].mean().sort_values(ascending=False)

Category
1.9                    19.000000
EVENTS                  4.435556
EDUCATION               4.389032
ART_AND_DESIGN          4.358065
BOOKS_AND_REFERENCE     4.346067
PERSONALIZATION         4.335987
PARENTING               4.300000
GAME                    4.286326
BEAUTY                  4.278571
HEALTH_AND_FITNESS      4.277104
SHOPPING                4.259664
SOCIAL                  4.255598
WEATHER                 4.244000
SPORTS                  4.223511
PRODUCTIVITY            4.211396
HOUSE_AND_HOME          4.197368
FAMILY                  4.192272
PHOTOGRAPHY             4.192114
AUTO_AND_VEHICLES       4.190411
MEDICAL                 4.189143
LIBRARIES_AND_DEMO      4.178462
FOOD_AND_DRINK          4.166972
COMMUNICATION           4.158537
COMICS                  4.155172
NEWS_AND_MAGAZINES      4.132189
FINANCE                 4.131889
ENTERTAINMENT           4.126174
BUSINESS                4.121452
TRAVEL_AND_LOCAL        4.109292
LIFESTYLE               4.094904
VIDEO_PLAYERS           4.063750
MAPS_AND_NAVIGATION     4.051613
TOOLS                   4.047411
DATING                  3.970769
Name: Rating, dtype: float64

# Number of apps having 5 star rating

In [45]:
(df['Rating']==5.0).sum()

274

# Average value of reviews

In [46]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [49]:
df[df['Reviews']=='3.0M']

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10472,Life Made WI-Fi Touchscreen Photo Frame,1.9,19.0,3.0M,"1,000+",Free,0,Everyone,NaN,"February 11, 2018",1.0.19,4.0 and up,NaN

In [51]:
df['Reviews']=df['Reviews'].replace('3.0M',3.0)

In [53]:
df[df['Reviews']==3.0]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10472,Life Made WI-Fi Touchscreen Photo Frame,1.9,19.0,3.0,"1,000+",Free,0,Everyone,NaN,"February 11, 2018",1.0.19,4.0 and up,NaN

In [54]:
df['Reviews']=df['Reviews'].astype('float')

In [55]:
df['Reviews'].mean()

444111.9265750392

# Get the number number of free and paid apps

In [63]:
len(df[df['Type']=='Paid'])

0

In [64]:
df['Type'].value_counts()

Free    10841
Name: Type, dtype: int64

# Which app has maximum reviews

In [73]:
df[df['Reviews'].max()==df['Reviews']]['App']

2544    Facebook
Name: App, dtype: object

# Top 5 app having highest reviews

In [92]:
index=df['Reviews'].sort_values(ascending=False).head().index

In [93]:
df.iloc[index]['App']

2544              Facebook
3943              Facebook
381     WhatsApp Messenger
336     WhatsApp Messenger
3904    WhatsApp Messenger
Name: App, dtype: object

# Find average rating of free and paid apps

In [97]:
df.groupby('Type')['Rating'].mean()

Type
Free    4.193338
Name: Rating, dtype: float64

# Display top 5 apps having maximum installs

In [5]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [6]:
df['Installs'].dtype

dtype('O')

In [7]:
df['Installs_1']=df['Installs'].str.replace(',','')

In [8]:
df.head(1)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Installs_1
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up,10000+

In [9]:
df['Installs_1'] = df['Installs_1'].str.replace('+', '', regex=True)

In [10]:
df.head(1)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Installs_1
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up,10000

In [11]:
df['Installs_1'].dtype

dtype('O')

In [12]:
df['Installs_1'].astype('int')

ValueError: invalid literal for int() with base 10: 'Free'

Here there a row that consist keyword of Free due to which above error occur

In [149]:
df[df['Installs_1']=='Free']

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Installs_1
10472,Life Made WI-Fi Touchscreen Photo Frame,1.9,19.0,3.0,"1,000+",Free,Free,Everyone,NaN,"February 11, 2018",1.0.19,4.0 and up,NaN,Free

In [151]:
df['Installs_1']=df['Installs_1'].str.replace('Free','0')

In [154]:
df[df['Installs_1']=='0']

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Installs_1
4465,Popsicle Launcher for Android P 9.0 launcher,PERSONALIZATION,NaN,0.0,5.5M,0+,Free,$1.49,Everyone,Personalization,"July 11, 2018",1.1,4.2 and up,0
5307,Ak Parti Yardım Toplama,SOCIAL,NaN,0.0,8.7M,0+,Free,$13.99,Teen,Social,"July 28, 2017",3.4.4.3.3,4.1 and up,0
5486,AP Series Solution Pro,FAMILY,NaN,0.0,7.4M,0+,Free,$1.99,Everyone,Education,"July 30, 2017",1.3,4.0 and up,0
5945,Ain Arabic Kids Alif Ba ta,FAMILY,NaN,0.0,33M,0+,Free,$2.99,Everyone,Education,"April 15, 2016",1.0,3.0 and up,0
6692,cronometra-br,PRODUCTIVITY,NaN,0.0,5.4M,0+,Free,$154.99,Everyone,Productivity,"November 24, 2017",1.0.0,4.1 and up,0
7434,Pekalongan CJ,SOCIAL,NaN,0.0,5.9M,0+,Free,0,Teen,Social,"July 21, 2018",0.0.1,4.4 and up,0
8081,CX Network,BUSINESS,NaN,0.0,10M,0+,Free,0,Everyone,Business,"August 6, 2018",1.3.1,4.1 and up,0
8614,Sweden Newspapers,NEWS_AND_MAGAZINES,NaN,0.0,2.1M,0+,Free,0,Everyone,News & Magazines,"July 7, 2018",1.1,4.4 and up,0
8871,Test Application DT 02,ART_AND_DESIGN,NaN,0.0,1.2M,0+,Free,0,Everyone,Art & Design,"March 14, 2017",4.0,4.2 and up,0
9148,Command & Conquer: Rivals,FAMILY,NaN,0.0,Varies with device,0,Free,0,Everyone 10+,Strategy,"June 28, 2018",Varies with device,Varies with device,0
9337,EG | Explore Folegandros,TRAVEL_AND_LOCAL,NaN,0.0,56M,0+,Free,$3.99,Everyone,Travel & Local,"January 22, 2017",1.1.1,4.1 and up,0
9719,EP Cook Book,MEDICAL,NaN,0.0,3.2M,0+,Free,$200.00,Everyone,Medical,"July 26, 2015",1.0,3.0 and up,0
9905,Eu sou Rico,FINANCE,NaN,0.0,2.6M,0+,Free,$30.99,Everyone,Finance,"January 9, 2018",1.0,4.0 and up,0
9917,Eu Sou Rico,FINANCE,NaN,0.0,1.4M,0+,Free,$394.99,Everyone,Finance,"July 11, 2018",1.0,4.0.3 and up,0
9934,I'm Rich/Eu sou Rico/أنا غني/我很有錢,LIFESTYLE,NaN,0.0,40M,0+,Free,$399.99,Everyone,Lifestyle,"December 1, 2017",MONEY,4.1 and up,0
10472,Life Made WI-Fi Touchscreen Photo Frame,1.9,19.0,3.0,"1,000+",Free,Free,Everyone,NaN,"February 11, 2018",1.0.19,4.0 and up,NaN,0

In [157]:
df['Installs_1'].astype('int')

0           10000
1          500000
2         5000000
3        50000000
4          100000
           ...
10836        5000
10837         100
10838        1000
10839        1000
10840    10000000
Name: Installs_1, Length: 10841, dtype: int32

In [163]:
index=df['Installs_1'].sort_values(ascending=False).head().index

In [164]:
df.iloc[index]['App']

7536    Security Master - Antivirus, VPN, AppLock, Boo...
474                           LINE: Free Calls & Messages
5596                                       Samsung Health
371                 Google Duo - High Quality Video Calls
3767                         Flipboard: News For Our Time
Name: App, dtype: object